"use client";

import { useReports } from "@/hooks/usePlatform";
import { FileText, Download, Calendar, Archive, PlusCircle } from "lucide-react";
import { format } from "date-fns";
import { PageHeader, EmptyState, ErrorState, TableSkeleton } from "@/components/common/AdminUI";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ReportsWorkspace } from "@/components/common/ReportsWorkspace";

export default function ReportsPage() {
  const { data, isLoading, isError, refetch } = useReports();
  const reports = data?.data ?? [];

  return (
    <div className="max-w-5xl space-y-6">
      <PageHeader
        title="Reports"
        subtitle="Platform and institution reports"
      />

      <Tabs defaultValue="builder" className="w-full">
        <TabsList className="bg-muted/60 p-1 rounded-xl mb-4">
          <TabsTrigger value="builder" className="text-xs rounded-lg py-1 px-3 flex items-center gap-1.5">
            <PlusCircle className="h-3.5 w-3.5" /> Report Builder
          </TabsTrigger>
          <TabsTrigger value="archive" className="text-xs rounded-lg py-1 px-3 flex items-center gap-1.5">
            <Archive className="h-3.5 w-3.5" /> System Archive ({reports.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="builder" className="mt-0">
          <ReportsWorkspace userRole="Platform Admin" />
        </TabsContent>

        <TabsContent value="archive" className="mt-0">
          {isError ? (
            <ErrorState error="Failed to load reports" onRetry={refetch} />
          ) : isLoading ? (
            <Card><CardContent className="p-6"><TableSkeleton rows={6} cols={4} /></CardContent></Card>
          ) : reports.length === 0 ? (
            <EmptyState
              icon={<FileText className="h-14 w-14" />}
              title="No reports available"
              description="Reports will appear here once generated by the system."
            />
          ) : (
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {reports.map((report) => (
                <Card key={report.id} className="hover:shadow-md transition-shadow border-border/60">
                  <CardContent className="p-5">
                    <div className="flex items-start gap-3 mb-3">
                      <div className="p-2 bg-primary/10 rounded-lg shrink-0">
                        <FileText className="h-4 w-4 text-primary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">{report.title}</p>
                        <span className="text-[10px] px-1.5 py-0.5 bg-secondary rounded text-secondary-foreground font-medium uppercase tracking-wide">
                          {report.type}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-1.5 text-xs text-muted-foreground mb-3">
                      <Calendar className="h-3.5 w-3.5" />
                      {format(new Date(report.created_at), "PPP")}
                    </div>
                    <Button variant="outline" size="sm" className="w-full gap-1.5 rounded-lg text-xs">
                      <Download className="h-3.5 w-3.5" /> Download
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
